version: '3'

services:

  campaign-db:
    image: microsoft/mssql-server-windows-express:1709
    ports:
      - "1433:1433"
    env_file:
      - db/eula.env
      - db/secrets.env

  campaign-web:
    image: devforum.azurecr.io/campaign-web-image
    depends_on:
      - nats

  campaign-nginx:
    image: devforum.azurecr.io/campaign-nginx-image
    ports:
    - "80:80"
    depends_on:
    - campaign-web

  nats:
    image: devforum.azurecr.io/nats

  campaign-worker:
    image: devforum.azurecr.io/campaign-worker-image
    depends_on:
      - nats
      - campaign-db