# First create an image with the Visual Studio Tools installed in it
# https://blogs.msdn.microsoft.com/heaths/2017/09/18/installing-build-tools-for-visual-studio-2017-in-a-docker-container/
FROM dockerdemo-msbuild:latest as builder

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

ADD ["./QRCode/bin/debug/QRCode.dll", "/Program Files (x86)/QRCode/QRCode.dll"]

RUN New-Item -Path HKLM:\SOFTWARE\QRCodeSystems\QRGenerator -Force; \
    Set-ItemProperty -Path HKLM:\SOFTWARE\QRCodeSystems\QRGenerator -Name LicenceKey -Value OurLicenceKeyGoesHere -Type String;

ADD . /src

WORKDIR /src
RUN msbuild

# https://hub.docker.com/r/microsoft/aspnet/
FROM microsoft/aspnet

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';"]
COPY --from=builder /src/PrecompiledWeb/Campaign/ /inetpub/wwwroot

HEALTHCHECK --interval=5s                                                    \
	CMD powershell -command                                                  \
		try {                                                                \
			$response = Invoke-WebRequest http://localhost -UseBasicParsing; \
			if ($response.StatusCode -eq 200) { return 0; }                  \
			else { return 1; }                                               \
		}                                                                    \
		catch {                                                              \
			return 1;                                                        \
		}